models/Product.php
<?php
/**
 * Created by PhpStorm.
 * User: Светлый
 * Date: 02.01.2018
 * Time: 17:22
 */

namespace app\models;


use yii\db\ActiveRecord;

class Product extends ActiveRecord
{
    public function behaviors()
    {

        return[
            'image' => [
                'class' => 'rico\yii2images\behaviors\ImageBehave',
            ]
        ];

    }

    public function getCategory(){

        return $this->hasOne(Category::className(), ['id' => 'category_id']);
    }

}

controllers/CartController.php
<?php
/**
 * Created by PhpStorm.
 * User: Светлый
 * Date: 05.01.2018
 * Time: 13:20
 */

namespace app\controllers;
use app\models\Product;
use app\models\Cart;
use Yii;
use app\models\OrderItems;
use app\models\Order;

class CartController extends AppController
{


    public function actionAdd(){

        $id = Yii::$app->request->get('id');
        $qty = (int)Yii::$app->request->get('qty');
        $qty = !$qty ? 1 : $qty;
        $product = Product::findOne($id);
        if(empty($product)) return false;
        $session = Yii::$app->session;
        $session->open();
        $cart = new Cart();
        $cart->addToCart($product, $qty);
        if (!Yii::$app->request->isAjax){
            return $this->redirect(Yii::$app->request->referrer);
        }

        $this->layout = false;

        return $this->render('cart-modal',  compact('session'));

}


    public function actionClear(){

        $session = Yii::$app->session;
        $session->open();
        $session->remove('cart');
        $session->remove('cart.qty');
        $session->remove('cart.sum');

        $this->layout = false;

        return $this->render('cart-modal',  compact('session'));
    }

    public function actionDelItem(){


        $id = Yii::$app->request->get('id');
        $session = Yii::$app->session;
        $session->open();
        $cart = new Cart();
        $cart->recalc($id);
        $this->layout = false;
        return $this->render('cart-modal',  compact('session'));


    }


    public function actionShow(){


        $id = Yii::$app->request->get('id');
        $session = Yii::$app->session;
        $session->open();
        $this->layout = false;
        return $this->render('cart-modal',  compact('session'));



    }


    public function actionView(){

        $session = Yii::$app->session;
        $session->open();
        $this->setMeta('Корзина');
        $order = new Order();

        if($order->load(Yii::$app->request->post())){

              $order->qty = $session['cart.qty'];
            $order->sum = $session['cart.sum'];


            if($order->save()){
               $this->saveOrderItems($session['cart'], $order->id);
                Yii::$app->session->setFlash('success', 'ваш заказ принят. Менеджер вскоре свяжется с вами');
                Yii::$app->mailer->compose('order', compact('session'))
                    ->setFrom('olegplaksin1998@gmail.ru')
                    ->setTo($order->email)
                    ->setSubject('заказ')
                    ->send();

                $session->remove('cart');
                $session->remove('cart.qty');
                $session->remove('cart.sum');
                return $this->refresh();
            } else {
                Yii::$app->session->setFlash('error', 'ошибка оформление заказа');

            }

        }


        return $this->render('view',  compact('session', 'order'));


    }
           protected function saveOrderItems($items, $order_id){

                 foreach ($items as $id => $item){
                     $order_items = new OrderItems();
                     $order_items->order_id = $order_id;
                     $order_items->product_id = $id;
                     $order_items->name = $item['name'];
                     $order_items->price = $item['price'];
                     $order_items->qty_item = $item['qty'];
                     $order_items->sum_item = $item['qty'] * $item['price'];
                     $order_items->save();
                 }

           }

}

controllers/CategoryController.php
<?php
/**
 * Created by PhpStorm.
 * User: Светлый
 * Date: 03.01.2018
 * Time: 13:12
 */

namespace app\controllers;
use app\models\Category;
use app\models\Product;
use Codeception\Util\Debug;
use Yii;
use yii\data\Pagination;

class CategoryController  extends AppController
{


    public function actionIndex(){


        $hits = Product::find()->where(['hit' => '1'])->limit(6)->all();

        $this->setMeta('E-Shoper');

      return $this->render('index', compact('hits'));
    }




    public function actionView($id){


        //$id = Yii::$app->request->get('id');
      //  debag($id);
     //   $products = Product::find()->where(['category_id' => $id])->all();

        $category = Category::findOne($id);

        if (empty($category)) {
            throw new \yii\web\HttpException(404, 'Такой категории нет или она была.');
        }

        $query = Product::find()->where(['category_id' => $id]);
        $pages = new Pagination(['totalCount' => $query->count(), 'pageSize' =>3, 'forcePageParam' => false, 'pageSizeParam' =>false]);
        $products = $query->offset($pages->offset)->limit($pages->limit)->all();

        $this->setMeta('E-Shoper | ' . $category->name, $category->keywords, $category->description);

        return $this->render('view', compact('products','pages', 'category'));

    }



    public function actionSearch(){


        $q = trim(Yii::$app->request->get('q'));

        $this->setMeta('E-Shoper | Поиск ' . $q);


        if(!$q)
            return $this->render('search');
        //  debag($id);
        //   $products = Product::find()->where(['category_id' => $id])->all();


        $category = Category::findOne($q);


        $query = Product::find()->where(['like', 'name', $q]);
        $pages = new Pagination(['totalCount' => $query->count(), 'pageSize' =>3, 'forcePageParam' => false, 'pageSizeParam' =>false]);
        $products = $query->offset($pages->offset)->limit($pages->limit)->all();

        $this->setMeta('E-Shoper | ' . $category->name, $category->keywords, $category->description);

        return $this->render('search', compact('products', 'pages', 'q'));

    }


}

controllers/ProductController.php
<?php
/**
 * Created by PhpStorm.
 * User: Светлый
 * Date: 04.01.2018
 * Time: 17:36
 */

namespace app\controllers;



use app\models\Product;
use app\models\Category;
use Yii;

class ProductController extends AppController
{

    public function actionView($id){



     //   $id = Yii::$app->request->get('id');


        $product = Product::findOne($id);

        if (empty($product)) {
            throw new \yii\web\HttpException(404, 'Такой товара нет или она был.');
        }

        $hits = Product::find()->where(['hit' => '1'])->limit(6)->all();
      //  $product = Product::find()->with('category')->where(['id' => $id])->one();

        return $this->render('view', compact('product', 'hits'));
    }


}

views/product/view.php
<?
use yii\helpers\Html;
use yii\widgets\LinkPager;
?>


<section>
    <div class="container">
        <div class="row">
            <div class="col-sm-3">
                <div class="left-sidebar">
                    <h2>Category</h2>
                    <div class="panel-group category-products""><!--category-productsr-->
                    <div class="panel panel-default">
                        <ul class="catalog"><?=\app\components\MenuWidget::widget(['tpl' => 'menu'])?></ul>
                    </div>
                </div><!--/brands_products-->
                    <div class="brands_products"><!--brands_products-->
                        <h2>Brands</h2>
                        <div class="brands-name">
                            <ul class="nav nav-pills nav-stacked">
                                <li><a href=""> <span class="pull-right">(50)</span>Acne</a></li>
                                <li><a href=""> <span class="pull-right">(56)</span>Grüne Erde</a></li>
                                <li><a href=""> <span class="pull-right">(27)</span>Albiro</a></li>
                                <li><a href=""> <span class="pull-right">(32)</span>Ronhill</a></li>
                                <li><a href=""> <span class="pull-right">(5)</span>Oddmolly</a></li>
                                <li><a href=""> <span class="pull-right">(9)</span>Boudestijn</a></li>
                                <li><a href=""> <span class="pull-right">(4)</span>Rösch creative culture</a></li>
                            </ul>
                        </div>
                    </div><!--/brands_products-->

                    <div class="price-range"><!--price-range-->
                        <h2>Price Range</h2>
                        <div class="well">
                            <input type="text" class="span2" value="" data-slider-min="0" data-slider-max="600" data-slider-step="5" data-slider-value="[250,450]" id="sl2" ><br />
                            <b>$ 0</b> <b class="pull-right">$ 600</b>
                        </div>
                    </div><!--/price-range-->

                    <div class="shipping text-center"><!--shipping-->
                        <img src="/images/home/shipping.jpg" alt="" />
                    </div><!--/shipping-->

                </div>
            </div>


        <? $mainImg = $product->getImage() ?>
        <?

        ?>
        <? $gallery = $product->getImages()?>


            <div class="col-sm-9 padding-right">
                <div class="product-details"><!--product-details-->
                    <div class="col-sm-5">
                        <div class="view-product">

                            <?= Html::img($mainImg->getUrl(), ['alt' => $product->name])?>
                            <h3>ZOOM</h3>
                        </div>
                        <div id="similar-product" class="carousel slide" data-ride="carousel">

                            <!-- Wrapper for slides -->
                            <div class="carousel-inner">

                                <? $count = count($gallery); $i = 0; foreach ($gallery as $img):?>

                                    <? if($i % 3 ==0):?>

                                <div class="item <? if($i == 0) echo 'active'?>">
                                    <? endif;?>
                                    <?= Html::img($img->getUrl('84x85'), ['alt' => ''])?>



                                <? $i++; if($i % 3 ==0 || $i == $count):?>
                            </div>
                            <? endif;?>
                            <? endforeach;?>
                            </div>


                            <!-- Controls -->
                            <a class="left item-control" href="#similar-product" data-slide="prev">
                                <i class="fa fa-angle-left"></i>
                            </a>
                            <a class="right item-control" href="#similar-product" data-slide="next">
                                <i class="fa fa-angle-right"></i>
                            </a>
                        </div>

                    </div>
                    <div class="col-sm-7">
                        <div class="product-information"><!--/product-information-->

                            <? if($product->new):?>

                                <?= Html::img("@web/images/product-details/new.jpg", ['class' => 'newarrival']) ?>

                            <? endif?>




                            <h2><?=$product->name?></h2>
                            <p>Web ID: 1089772</p>
                            <img src="/images/product-details/rating.png" alt="" />
                            <span>
									<span>US $<?=$product->price?></span>
									<label>Quantity:</label>
									<input type="text" value="1" id="qty" />
									<a href="<?=\yii\helpers\Url::to(['cart/add', 'id' => $product->id])?>" data-id="<?=$product->id?>" class="btn btn-fefault cart add-to-cart">
										<i class="fa fa-shopping-cart"></i>
										Add to cart
									</a>
								</span>
                            <p><b>Brand:</b><a href="<?= \yii\helpers\Url::to(['category/view', 'id' => $product->category->id])?>"><?=$product->category->name?></a></p>
                            <a href=""><img src="/images/product-details/share.png" class="share img-responsive"  alt="" /></a>
                        </div><!--/product-information-->
                    </div>
                </div><!--/product-details-->




                <div class="recommended_items"><!--recommended_items-->
                    <h2 class="title text-center">recommended items</h2>

                    <div id="recommended-item-carousel" class="carousel slide" data-ride="carousel">
                        <div class="carousel-inner">

                            <? $count = count($hits); $i = 0; foreach ($hits as $hit):?>



                                <? if($i % 3 == 0):?>

                            <div class="item <?if($i == 0) echo 'active'?>">

                               <?endif;?>



                                <div class="col-sm-4">
                                    <div class="product-image-wrapper">
                                        <div class="single-products">
                                            <div class="productinfo text-center">
                                                <?= Html::img("@web/images/products/{$hit->img}", ['alt' => $hit->name])?>

                                                <h2>$<?=$hit->price?></h2>
                                                <p><a href="<?=\yii\helpers\Url::to(['product/view', 'id' => $hit->id])?>"><?=$hit->name?></a> </p>
                                                <a class="btn btn-default add-to-cart cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>


                                <?$i++; if($i % 3 == 0 || $i == $count):?>

                            </div>

                                <?endif;?>
                            <?php endforeach;?>


                        </div>
                        <a class="left recommended-item-control" href="#recommended-item-carousel" data-slide="prev">
                            <i class="fa fa-angle-left"></i>
                        </a>
                        <a class="right recommended-item-control" href="#recommended-item-carousel" data-slide="next">
                            <i class="fa fa-angle-right"></i>
                        </a>
                    </div>
                </div><!--/recommended_items-->

            </div>
        </div>
    </div>
</section>